site_name: Ezoria MVP Docs
site_description: Stakeholder-ready MVP research, plan, and slides
site_url: https://googleeer.github.io/ezoria/
nav:
  - Home: index.md
  - Research: research.md
  - Slides: slides.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
